on:
  push:
  pull_request:
  
jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'
          
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: install packages required for app # Set up R env to install packages
        run: |
          install.packages('remotes')
          install.packages('shiny')
          install.packages('shinydashboard')
          install.packages('dplyr')
          install.packages('leaflet')
          install.packages('readxl')
          install.packages('leaflet.extras')
          install.packages('leaflegend')
          install.packages('timevis')
          install.packages('reshape2')
          install.packages('DT')
          install.packages('ggplot2')
          install.packages('shinyjs')
          install.packages('testthat')
          install.packages('rlang')

        shell: Rscript {0}

      - name: Source app.R # Run the script
        run: source("app.R")
        shell: Rscript {0}

  
      - name: Generate data # Run the script
        run: source("unit_tests/test_cleaned_data.R")
        shell: Rscript {0}
