on:
  push:
  pull_request:
  
permissions: write-all
  
name: run-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'
          
      - name: Setup renv # Set up R env to install packages
        run: |
          install.packages('remotes')
          install.packages('curl')
          install.packages('renv')
        shell: Rscript {0}
        
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install Gdal
        run: sudo apt install libgdal-dev             
        
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install dependencies # Install the dependencies eg. Dplyr, tidyverse etc
      
        run: renv::restore()
        shell: Rscript {0}
        
      - name: Run tests
        shell: Rscript {0}
        run: |
          source('unit_tests/test_cleaned_data.R')
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: artifacts/code-coverage.html
