on:
  push:
  pull_request:
  
jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'

      - name: Source app.R # Run the script
        run: source("app.R")
        shell: Rscript {0}

  
      - name: Tests # Run the script
        run: source("unit_tests/test_cleaned_data.R")
        shell: Rscript {0}
